# Site settings
title: "Mike Conley's Bug Notes"
email: mconley@mozilla.com
description: "A place where I publish my raw, unedited notes on completed bugs."
baseurl: "http://people.mozilla.org/~mconley2/bugnotes"
url: "http://people.mozilla.org/~mconley2/bugnotes"
twitter_username: mike_conley
github_username:  mikeconley

# Build settings
markdown: kramdown
permalink: /:title.html

exclude: [exports, Gruntfile.js, node_modules, scripts]
